### ISSUE TITLE
Osi doesn't properly link with GLPK

### ISSUE THREAD

**Issue by tkralphs** [coin-or-tools/homebrew-coinor#20]
Although the recipe for `Osi` includes an option for linking with `Glpk`, it won't work, since we aren't passing the proper arguments to `configure` to make that happen. There is also a question about whether we should in fact be linking to the "official" Glpk or the specific version that the current `OsiGlpk` implementation is meant to work with (not usually the latest one).

**Comment by dpo** [comment]
Is this resolved now?

**Comment by tkralphs** [comment]
Yes.
