### ISSUE TITLE
Update solvers

### ISSUE THREAD

**Issue by dirkschumacher** [coin-or-tools/homebrew-coinor#45]
I updated some solvers to their latest version in my fork (https://github.com/dirkschumacher/homebrew-coinor) and also enabled cbc-parallel (#44). Does anything speaks against sending a pull request? I am happy to contribute some time here.

**Comment by tkralphs** [comment]
Sure, go ahead and submit PRs, thanks!

**Comment by dpo** [comment]
All done in the last salvo of pull requests. Thank you.
