### ISSUE TITLE
Unable to install CBC

### ISSUE THREAD

**Issue by AlexeySizanov** [coin-or-tools/homebrew-coinor#60]
I am trying to install cbc using homebrew.

Here is the output:
Cloning into '/usr/local/Homebrew/Library/Taps/coin-or-tool/homebrew-coinor'...
Username for 'https://github.com': AlexeySizanov
Password for 'https://AlexeySizanov@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/coin-or-tool/homebrew-coinor/' not found
Error: Failure while executing; `git clone https://github.com/coin-or-tool/homebrew-coinor /usr/local/Homebrew/Library/Taps/coin-or-tool/homebrew-coinor --depth=1` exited with 128.

**Comment by tkralphs** [comment]
Oops, there was a typo in my last commit. Can you try now?

**Comment by tkralphs** [comment]
Ah, yes, sorry, I was on my way out the door and didn't check carefully enough! Now I hope it should be fully fixed.

**Comment by AlexeySizanov** [comment]
It works. Thanks!
