### ISSUE TITLE
Installing Clp with the --with-glpk flag doesn't work from homebrew, while working from coinbrew

### ISSUE THREAD

**Issue by Alexander-Belyi** [coin-or-tools/homebrew-coinor#75]
When running
```bash
brew install coin-or-tools/coinor/clp --with-glpk
```
the process stops with
```bash
Error: coin-or-tools/coinor/clp 1.17.7 did not build
```
The last error I see in the output is
```bash
configure: error: Cannot find file amd.h in /private/tmp/clp-20220201-11165-16r7a0d/Clp-releases-1.17.7/Clp
```

**Comment by dpo** [comment]
The `--with-glpk` option was removed. Glpk is now built by default. In addition, you may be able to benefit from the precompiled binaries now. Could you confirm that you're able to install clp?
