### ISSUE TITLE
Issue with installing dylp on Mac with GH actions.

### ISSUE THREAD

**Issue by jaseeverett** [coin-or-tools/homebrew-coinor#97]
Thanks @tkralphs for fixing #96 . I was getting this error as well for the past few weeks as part of a GitHub action installing symphony. It is now fixed. However, I am now getting an error trying to install dylp as part of this code
```
brew tap coin-or-tools/coinor
brew install coin-or-tools/coinor/symphony
```
The actual code is here:
https://github.com/MathMarEcol/spatialplanr/blob/0ead5916920ecc0c3d7a3f69ef0a4bf3a5943f9b/.github/workflows/MacOS.yaml#L38-L42

The error can be seen from here: https://github.com/MathMarEcol/spatialplanr/actions/runs/8965445714/job/24618951632#step:5:239

Any suggestions appreciated.

**Comment by jaseeverett** [comment]
Apologies, but I'm hoping there is a fix if I can implement to get dylp installing on Mac OS on Apple Silicon as part of my GitHub action? Do you need further information?

I am attempting to [install symphony](https://github.com/MathMarEcol/spatialplanr/blob/0ead5916920ecc0c3d7a3f69ef0a4bf3a5943f9b/.github/workflows/MacOS.yaml#L38-L42) using 
```
- name: Install system dependencies
        run: |
          brew install pkg-config
          brew tap coin-or-tools/coinor
          brew install coin-or-tools/coinor/symphony
```

The specific [error is](https://github.com/MathMarEcol/spatialplanr/actions/runs/8965445714/job/24618951632#step:5:239):

```
==> Installing coin-or-tools/coinor/dylp
==> ./configure --datadir=/opt/homebrew/Cellar/dylp/1.10.4_1/share/dylp --includ
==> make
Last 15 lines from /Users/runner/Library/Logs/Homebrew/dylp/02.make:
 clang -DHAVE_CONFIG_H -I. -I. -I../../src/DylpStdLib -I./../DylpStdLib -O3 -pipe -DNDEBUG -Wimplicit -Wparentheses -Wsequence-point -Wreturn-type -Wcast-qual -Wall -Wno-unknown-pragmas -Wno-long-long -DDYLP_BUILD -fno-strict-aliasing -c dy_bound.c  -fno-common -DPIC -o .libs/dy_bound.o
dy_consys_utils.c:830:7: error: call to undeclared function 'unavailable'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  if (finite(infinity)) setflg(consys->opts,CONSYS_FININF) ;
      ^
./dy_vector.h:201:17: note: expanded from macro 'finite'
# define finite DYLP_ISFINITE
                ^
../../src/DylpStdLib/config.h:40:23: note: expanded from macro 'DYLP_ISFINITE'
#define DYLP_ISFINITE unavailable
                      ^
1 error generated.
make[2]: *** [dy_consys_utils.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

```

**Comment by tkralphs** [comment]
There has been a lot of discussion about this over time in these two issues: 
https://github.com/coin-or-tools/homebrew-coinor/issues/80
https://github.com/coin-or/DyLP/issues/18
A fix does not seem trivial. I'm honestly not sure why DyLP is listed as a dependency of SYMPHONY except that it can, in principle, be used as the LP solver within SYMPHONY's branch and bound. In any case, SYMPHONY should work just fine without DyLP, so the easiest fix is just simply to remove the dependency. If you know how to edit a recipe file using `brew edit`, you can just remove that line and then I guess everything will be OK. I will open a PR to do this as well and see if everything seems to be OK.

**Comment by tkralphs** [comment]
I opened #98 but I'm having a different issue that I can't quite wrap my head around.

**Comment by jaseeverett** [comment]
Thanks for your help @tkralphs . Apologies for the slow reply. I was working on other things. It seems symphony doesn't need dylp anymore. Removing that from my gh action has solved the issue while still allowing symphony to run. Thanks so much.

**Comment by tkralphs** [comment]
Yes, thanks for coming back to this. After some struggles unrelated to this, it's finally all working!
